### ISSUE TITLE
New  (and/or renamed) data fields 

### ISSUE THREAD

**Issue by gautamvenugopalan** [stanfordbeads/OptLevAnalysis#6]
Circa June 2024, a few important changes have been made to the data acquisition programs. I suppose one could maintain backward compatibility using a dictionary and some try/except statements but I leave it up to you @clarkehardy if/how you want to.

- `seismometer` field has been removed in favor of `acc` (abbreviation for accelerometer), since this is what the instrument(s) actually is(are).
- `acc` is a $3 \times n_{\mathrm{samples}}$ array, since we are now recording 3 accelerometers, one for each cartesian coordinate) (we may yet change the number depending on the usefulness).
- `PSPD` key has been removed in favor of `DCQPD` since this is what it is.
- A new field `camEXPstat` has been added. This is supposed to be a TTL like signal that flips between HI and LO whenever a frame is acquired. May be useful for dignosing camera data quality, so perhaps this should be added to the AggregateData objects.
- The handling of the `spin_data` object is still in flux, we have yet to decide how we want to do this since if we actually want information about a $\sim 140\,\mathrm{kHz}$ signal, we need to digitize at twice that rate which may make the files un-necessarily bloated...

**Comment by clarkehardy** [comment]
All of these have been handled with the exception of the last point. We have never used `spin_data` previously, so if we do decide to use it then the code can be updated to do so in the future.
